name: build filesender

on:
  push:
    branches:
      - 'main'
    paths:
      - 'filesender/**'
      - '!filesender/README.md'
  schedule:
    # cron: 'min hour day month weekday'
    - cron: '0 4 * * 3'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'run action manually'

jobs:
  multi:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/login-action
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/docker/build-push-action
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./filesender
          file: ./filesender/Dockerfile
          # platforms: linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64
          platforms: linux/amd64
          push: true
          tags: |
            3x3cut0r/filesender:2.40-alpine
            3x3cut0r/filesender:latest
