name: build streamlit

on:
  push:
    branches:
      - 'main'
    paths:
      - 'streamlit/**'
  schedule:
    # cron: 'min hour day month weekday'
    - cron: '0 4 * * 3' # every wednesday on 04:00
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'run action manually'

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./streamlit
          file: ./streamlit/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            3x3cut0r/streamlit:latest

      - name: Run Docker Container to extract version
        id: docker_version
        run: |
          STREAMLIT_VERSION=$(docker run --rm 3x3cut0r/streamlit:latest sh -c "echo \$STREAMLIT_VERSION")
          echo "::set-output name=streamlit_version::$STREAMLIT_VERSION"

      - name: Push Docker image with tag
        run: |
          docker tag streamlit 3x3cut0r/streamlit:${{ steps.docker_build.outputs.streamlit_version }}
          docker push 3x3cut0r/streamlit:${{ steps.docker_build.outputs.streamlit_version }}
