name: build tvheadend-sundtek

on:
  push:
    branches:
      - 'main'
    paths:
      - 'tvheadend-sundtek/**'
  schedule:
    # cron: 'min hour day month weekday'
    - cron: '0 4 * * 3' # every wednesday on 04:00
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'run action manually'

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Version, commit and push changes
        run: |
          mkdir -p tvheadend-sundtek
          cd tvheadend-sundtek
          wget https://github.com/linuxserver/docker-tvheadend/releases
          cat releases | grep "releases/tag/" | head -n 1 > VERSION
          rm releases
          VERSION_STRING=$(cat VERSION | grep 'releases/tag/' | head -n 1)
          VERSION=${VERSION_STRING##*releases/tag/}
          echo $VERSION | cut -d '"' -f 1 > VERSION
          VERSION=$(cat VERSION)
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "version updated ($VERSION)"
          git push

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build without pushing
        uses: docker/build-push-action@v4
        with:
          context: ./tvheadend-sundtek
          file: ./tvheadend-sundtek/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          load: true # Das Image wird in den Docker Daemon geladen
          tags: 3x3cut0r/tvheadend-sundtek:latest

      - name: Get new image ID
        id: new_image_id
        run: echo "::set-output name=id::$(docker images --format '{{.ID}}' 3x3cut0r/tvheadend-sundtek:latest)"

      - name: Get existing image ID
        id: existing_image_id
        run: echo "::set-output name=id::$(docker pull 3x3cut0r/tvheadend-sundtek:latest && docker images --format '{{.ID}}' 3x3cut0r/tvheadend-sundtek:latest)"

      - name: Compare and push if different
        run: |
          if [ "${{ steps.new_image_id.outputs.id }}" != "${{ steps.existing_image_id.outputs.id }}" ]; then
            docker push 3x3cut0r/tvheadend-sundtek:latest
          else
            echo "Image has not changed. Not pushing."
          fi
