name: build tvheadend-sundtek

on:
  push:
    branches:
      - 'main'
    paths:
      - 'tvheadend-sundtek/**'
  schedule:
    # cron: 'min hour day month weekday'
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'run action manually'
        
jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        
      - name: Update Version
        run: |
          mkdir -p tvheadend-sundtek
          cd tvheadend-sundtek
          wget https://github.com/linuxserver/docker-tvheadend/releases
          cat releases | grep "releases/tag/" | head -n 1 > VERSION
          rm releases
          VERSION_STRING=$(cat version | grep 'releases/tag/' | head -n 1)
          VERSION=${VERSION_STRING##*releases/tag/}
          echo $VERSION | cut -d '"' -f 1 > VERSION
      - name: Commit and push changes
        run: |
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git add -A
          VERSION=$(cat VERSION)
          git commit -m "version updated ($VERSION)"
          git push
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./tvheadend-sundtek
          file: ./tvheadend-sundtek/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          tags: 3x3cut0r/tvheadend-sundtek:latest
